postgres:
  dsn: "postgres://postgres:postgres@db:5432/database"
  log_level: "info" # log level: silent, warn, info, error
  max_idle_conns: 5
  max_open_conns: 20
  conn_max_lifetime: "1h"
  ping_interval: "5000ms"
  retry_attempts: 3
redis:
  cache_host: "redis://redis:6379/4"
  worker_cache_host: "redis://redis:6379/5"
  dial_timeout: "2s"
  write_timeout: "4s"
  read_timeout: "4s"
#
#postgres:
#  dsn: "postgres://postgres:postgres@localhost:5432/database"
#  log_level: "info" # log level: silent, warn, info, error
#  max_idle_conns: 5
#  max_open_conns: 20
#  conn_max_lifetime: "1h"
#  ping_interval: "5000ms"
#  retry_attempts: 3
#redis:
#  cache_host: "redis://localhost:6379/4"
#  worker_cache_host: "redis://localhost:6379/5"
#  dial_timeout: "2s"
#  write_timeout: "4s"
#  read_timeout: "4s"
